name: internet_file_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  internet_file:
    path: ../

dev_dependencies:
  lints: ^6.0.0
